version: "3.3"
services:
  geth:
    build: .
    container_name: ethereum
    volumes:
      - ./config:/config
      - ./data:/data
    restart: always

  proxy:
    image: nginx:1.22-alpine
    container_name: rpcproxy
    ports:
      - "8545:8545"
    links:
      - geth
    volumes:
      - ./njs:/etc/nginx/njs
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - geth
    restart: always

  faucet:
    image: chainflag/eth-faucet:1.1.0
    container_name: ethfaucet
    environment:
      - WEB3_PROVIDER=http://geth:8545
    ports:
      - "8080:8080"
    links:
      - geth
    volumes:
      - ./config/keystore:/app/keystore
      - ./config/password.txt:/app/password.txt
    command: -wallet.keyjson /app/keystore -wallet.keypass /app/password.txt -faucet.minutes 1
    depends_on:
      - geth
    restart: always

networks:
  default:
